import { PL_ORIGIN, hostSiteUrl } from "@/lib/seo-host";
import { SITE_NAME, SITE_DISPLAY_NAME } from "@/lib/seo";
import { NAV_ITEMS } from "@/data/nav";

type JsonLdProps = {
  data: Record<string, unknown> | ReadonlyArray<Record<string, unknown>>;
  id?: string;
};

export default function JsonLd({ data, id }: JsonLdProps) {
  const json = JSON.stringify(data);
  return (
    <script
      type="application/ld+json"
      id={id}
      dangerouslySetInnerHTML={{ __html: json }}
    />
  );
}

// Stable entity @id — always PL regardless of serving domain
const ORG_ID = `${PL_ORIGIN}/#organization`;

// These three functions are now generated by SiteJsonLd (async Server Component).
// Kept here as no-origin legacy exports to avoid breaking any other import sites;
// they will emit PL_ORIGIN-based data. Do not use in new code.
export function organizationLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": ORG_ID,
    name: SITE_DISPLAY_NAME,
    alternateName: SITE_NAME,
    url: PL_ORIGIN,
    logo: `${PL_ORIGIN}/logo.png`,
    description:
      "Precision rail maintenance with uncompromised safety — operations across Poland, Ukraine, Türkiye, USA, South Korea, and Uzbekistan.",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Warsaw",
      addressCountry: "PL",
    },
    sameAs: [],
  };
}

export function websiteLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${PL_ORIGIN}/#website`,
    url: PL_ORIGIN,
    name: SITE_DISPLAY_NAME,
    alternateName: SITE_NAME,
    inLanguage: "en-US",
    publisher: { "@id": ORG_ID },
  };
}

/**
 * SiteNavigationElement — surfaces the primary navigation to Search so it has
 * clean candidates for sitelinks. Sitelinks are still chosen automatically by
 * Google; this only provides clear, machine-readable structure.
 */
export function siteNavigationLd() {
  const items = NAV_ITEMS.map((item, i) => ({
    "@type": "SiteNavigationElement",
    position: i + 1,
    name: item.label,
    url: `${PL_ORIGIN}${item.href}`,
  }));
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "@id": `${PL_ORIGIN}/#nav`,
    itemListElement: items,
  };
}

export function aboutPageLd(origin: string, description: string) {
  return {
    "@context": "https://schema.org",
    "@type": "AboutPage",
    url: hostSiteUrl(origin, "about"),
    name: `About — ${SITE_NAME}`,
    description,
    inLanguage: "en-US",
    mainEntity: { "@id": ORG_ID },
  };
}

export function serviceLd(
  origin: string,
  input: {
    slug: string;
    name: string;
    description: string;
  },
) {
  const { slug, name, description } = input;
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name,
    description,
    url: hostSiteUrl(origin, `solutions/${slug}`),
    provider: { "@id": ORG_ID },
    serviceType: "Rail maintenance",
    areaServed: [
      "Poland",
      "Ukraine",
      "Türkiye",
      "USA",
      "South Korea",
      "Uzbekistan",
    ],
  };
}

export function caseStudyLd(
  origin: string,
  input: {
    slug: string;
    name: string;
    description: string;
    country: string;
  },
) {
  const { slug, name, description, country } = input;
  const url = hostSiteUrl(origin, `portfolios/${slug}`);
  return {
    "@context": "https://schema.org",
    "@type": "CreativeWork",
    "@id": url,
    name,
    description,
    url,
    creator: { "@id": ORG_ID },
    contentLocation: { "@type": "Place", name: country },
    inLanguage: "en-US",
  };
}

type OfficeInput = {
  city: string;
  country: string;
  role: "headquarters" | "office" | "warehouse";
  lat: number;
  lng: number;
};

export function placesLd(offices: ReadonlyArray<OfficeInput>) {
  return offices.map((o) => ({
    "@context": "https://schema.org",
    "@type": o.role === "headquarters" ? "Organization" : "Place",
    name: `${SITE_NAME} — ${o.city}`,
    address: {
      "@type": "PostalAddress",
      addressLocality: o.city,
      addressCountry: o.country,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: o.lat,
      longitude: o.lng,
    },
  }));
}

type BreadcrumbItem = {
  name: string;
  path: string;
};

export function breadcrumbLd(
  origin: string,
  input: { trail: ReadonlyArray<BreadcrumbItem> },
) {
  const { trail } = input;
  const home: BreadcrumbItem = {
    name: "Home",
    path: "",
  };
  const items = [home, ...trail].map((crumb, i) => ({
    "@type": "ListItem",
    position: i + 1,
    name: crumb.name,
    item: hostSiteUrl(origin, crumb.path),
  }));
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items,
  };
}
